language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install: 
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install asyncio; fi
    - "pip install coveralls"
    - "pip install -r requirements/tests.txt"

script: "py.test --cov=yawf"
after_success: coveralls
